apiVersion: v1
kind: Secret
metadata:
  name: velero-backup-notification-secrets
type: Opaque
stringData:
  slack_webhook: {{ .Values.slack.webhook | quote }}
  slack_channel: {{ .Values.slack.channel | quote }}
  email_smtp_host: {{ .Values.email.smtp.host | quote }}
  email_smtp_port: {{ .Values.email.smtp.port | quote }}
  email_smtp_username: {{ .Values.email.smtp.username | quote }}
  email_smtp_password: {{ .Values.email.smtp.password | quote }}
